# Generated by Django 4.2.5 on 2023-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relink_app', '0002_alter_link_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='auto_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='seconds_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='url_broken',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
