# Generated by Django 4.2.5 on 2023-10-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relink_app', '0003_link_auto_redirect_link_seconds_wait_link_url_broken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='text_link',
            field=models.CharField(blank=True, default='', help_text='Texto que se mostrara como encabezado al acceder al enlace para ser redirigido', max_length=200, verbose_name='Texto de mostrador'),
        ),
        migrations.AlterField(
            model_name='link',
            name='auto_redirect',
            field=models.BooleanField(default=False, verbose_name='Redireccionar automaticamente'),
        ),
        migrations.AlterField(
            model_name='link',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=None, help_text='(Dejar en blanco para no tener fecha de expiración)', null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='title', help_text='Nombre para identificar al enlazador', max_length=50, verbose_name='Nombre del enlazador'),
        ),
        migrations.AlterField(
            model_name='link',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Esta activado'),
        ),
        migrations.AlterField(
            model_name='link',
            name='seconds_wait',
            field=models.IntegerField(default=0, verbose_name='Segundos a esperar'),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug (a acceder)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='URL (a redirigir)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url_broken',
            field=models.SmallIntegerField(default=0, verbose_name='Contador de avisos de enlace roto'),
        ),
    ]
